### PR TITLE
[bugfix] removed NPE when no Accept header is present

### PR DESCRIPTION
**Pull request by opax**

### CODE REVIEW

**Comment by adamretter** [comment]
So I complete agree we want to avoid an NPE. However, I am not convinced that the `produces` annotation should match if there is no Accept header. In the original RESTXQ paper it says:

```
'%rest:produces', which constrains a Resource Function, by only accepting requests
for which the mime-type matches the HTTP Accept Header
```

So `produces` is meant to enforce a constraint against the Accept header. So on one hand we could argue that if there is no Accept header, we cannot enforce the constraint and so we should not match. 

However, on the other hand, we could think about it as, what does the client Accept if it does not tell you? Presumably it accepts anything e.g. `*/*` as you have suggested.

Hmm I could kinda go either way on this. If we look at what the adjacent `%rest:accept` annotation does, then we see that it will not match requests where the header (Content-Type) is missing - https://github.com/exquery/exquery/blob/master/exquery-restxq/src/main/java/org/exquery/restxq/impl/annotation/ConsumesAnnotationImpl.java#L139

I think I would like to keep the behaviour of constraints annotations similar, and so I think most likely that the `%rest:produces` should **not** match if the Accept header is missing.

I could be persuaded though. Perhaps also @ChristianGruen has a view on this?

**Comment by ChristianGruen** [comment]
I just looked up [RFC 2616](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html); it says that "If no Accept header field is present, then it is assumed that the client accepts all media types.", so it should be fine to return `*/*` if the field is missing. Good to know, btw; I'm not sure what we did in BaseX..

**Comment by adamretter** [comment]
Good to know @ChristianGruen. In addition, I am just trying to determine what the JAX-RS 2.0 specification JSR-339 says with regards to this.

The first thing I can find is section 3.5, page 18:
```
An implementation MUST NOT invoke a method whose effective value of @Produces does not match the request Accept header.
```

The only other thing I can find is section 3.8, page 23:
```
4. Obtain the acceptable media types A. If A = {}, set A = {‘*/*’}
```

I am not sure that section 3.8 applies here, as this is about constructing a response rather than resource method selection. I will write a small example in Java to test how JAX-RS works in practice in this respect and report back.

**Comment by ChristianGruen** [comment]
Hm.. We could extend this and ask someone on the [JAX-RS mailing lists](https://java.net/projects/jax-rs-spec/lists), but I think we will be fine accepting all requests without Accept header. In practice, many client (like curl) send `Accept: */*` anyway if it's not explicitly specified by the user.

**Comment by opax** [comment]
If I may weigh in: I deemed it fine to accept everything in the absence of an accept header, as it is clearly the specified behavior in the HTTP specs (see http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html ):

"If no Accept header field is present, then it is assumed that the client accepts all media types. If an Accept header field is present, and if the server cannot send a response which is acceptable according to the combined Accept field value, then the server SHOULD send a 406 (not acceptable) response. "

**Comment by opax** [comment]
Btw.: It would be nice if restxq used the 406 status code as specified. 

At the moment, at least in eXist, a 405 error "HTTP method GET is not supported by this URL" is returned if a resource function for the path exists, but is not selected because of a mismatched Accept-header. This may be slightly confusing during development.

**Comment by opax** [comment]
And sorry Christian, I overlooked that you had already cited the RFC.

**Comment by adamretter** [comment]
I composed a small JAX-RS version 2.0 application, and it indeed shows that when the client sends `Accept: */*` and the resource function has a produces annotation, then the request is served.

```java
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;

@Path("/test")
public class TestRest {

    @GET
    @Path("/hello")
    @Produces("application/json")
    public String hello() {
        return "hello" + System.getProperty("line.separator");
    }
}
```

The results from curl:
```bash
$ curl -vv http://localhost:8080/resources/test/hello
* Hostname was NOT found in DNS cache
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> GET /resources/test/hello HTTP/1.1
> User-Agent: curl/7.39.0
> Host: localhost:8080
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Thu, 25 Jun 2015 15:16:41 GMT
< Content-Type: application/json
< Content-Length: 6
< Server: Jetty(9.3.0.v20150612)
< 
hello
* Connection #0 to host localhost left intact
```

**Comment by adamretter** [comment]
@opax Thanks for the PR and sorry for the delay.

**Comment by opax** [comment]
:)

**Pull request merged**
