### PR TITLE
RESTXQ: Update Version

### PR DESCRIPTION
**Pull request by ChristianGruen**
Minor notes:

Errors:
* Same namespace for restxq and errors

Paths:
* Added: "The path string MAY start and end with an optional slash."

Method Annotation, Request Bodies:
* Added: "An implementation MAY provide support for other input types
  such as HTML or JSON."

Response Format:
* Changed for http:response: reason → message

### CODE REVIEW

**Comment by adamretter** [comment]
Hi Christian, can you rebase this please. At the moment your two commits seem to include many changes that are unrelated to your pull-request topic. I think this is simple because you have not rebased, however this makes it very hard (if not impossible) to actually find and review your intended changes.

**Comment by ChristianGruen** [comment]
Sorry for that. You can find my [new version here](https://gist.github.com/ChristianGruen/1d7e52cd7865c5b99968); just close my pull request. Rebasing it would surely be the more elegant approach..

Does this help?

**Comment by adamretter** [comment]
I don't think I want to close your pull-request, otherwise how do I get your latest changes in?

**Comment by ChristianGruen** [comment]
My first thought was that you could simply take my gist version and push it by yourself. – But just wait, I'll try to make it work by myself.

**Comment by ChristianGruen** [comment]
https://github.com/exquery/exquery/pull/26 ...

**Pull request closed without merging**
