### PR TITLE
RESTXQ 1.0 Specification Updated

### PR DESCRIPTION
**Pull request by ChristianGruen**

### CODE REVIEW

**Comment by ChristianGruen** [comment]
Hi @adamretter! Any news regarding this pull request?

**Comment by adamretter** [comment]
@ChristianGruen I manually resolved and merged this. Thanks for your contribution and sorry for the huge delay.

To speed things up in future by making the review easier it would really help if you could do a series of small commits, there should be one commit for any layout (i.e. whitespace) formatting and then each change of intention should be in it's own related commit, i.e. all changes for `Content Type` -> `Media Type` would go into one commit, whereas removing comments from code examples would go into another.

Hopefully that makes sense? Basically smaller and more granular commits would help ;-)

Cheers Adam.

**Comment by ChristianGruen** [comment]
Thanks a lot for the merge.

> Hopefully that makes sense? Basically smaller and more granular commits would help ;-)

Absolutely! I’ll take care of this in future. Btw, could you also update http://exquery.org/spec/restxq and (ideally) add a link to it somewhere on the http://exquery.org/ site?

**Comment by adamretter** [comment]
@ChristianGruen You were just ahead of me ;-) I just merged the changes to the `gh-pages` branch too, so they are now live.

The EXQuery website is really out of date, I just added a couple of links as requested... but touching that site makes me itch to actually do something with it...

**Comment by ChristianGruen** [comment]
Thanks ;)

**Pull request closed without merging**
